services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/
      #- /var/www/html/
    depends_on:
      - db
      
  db:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=diblio
      - MARIADB_DB=diblio
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8088:80"
    depends_on:
      - db

volumes:
  db_data: